### ISSUE TITLE
[Feature Request] MCTS Issue tracker

### ISSUE THREAD

**Issue by vmoens** [pytorch/rl#2357]
- [ ] `break_when_all_done` in `env.rollout()` #2355
- [ ] Partial steps in env  #2356
  - [ ] `BatchedEnv`: pass the indices of envs where a step should be done  
  - [ ] `BatchedEnv`: index a BatchedEnv
  - [ ] Stateless env: discard done parts of the TD
- [ ] Scores
  - [x] PUCT
  - [x] UCB
  - [ ] UCB1_TUNED
  - [ ] EXP3
  - [ ] PUCT_VARIANT
- [x] `TensorSpec.enumerate()`
- [x] Storage
  - [x] Hashing functions
  - [x] Query modules
  - [x] Map
  - [x] MCTSForest
- [ ] Policy classes
  - [ ] MCTSPolicyBase
  - [ ] MCTSPolicy
  - [ ] AlphaGoPolicy
  - [ ] AlphaStarPolicy
  - [ ] MuZeroPolicy

**Comment by ParamThakkar123** [comment]
@vmoens I would like to work on this issue if it's open for contributions. Looks quite interesting!

**Comment by vmoens** [comment]
There's a PR open but I never really had the time to properly review it.

Feel free to branch out and pick it up! https://github.com/pytorch/rl/pull/2796

**Comment by ParamThakkar123** [comment]
Sure @vmoens ! Thank you!
