### ISSUE TITLE
[BUG] Incorrect shape requirements for categorical spaces

### ISSUE THREAD

**Issue by smorad** [pytorch/rl#894]
## Describe the bug

Two bugs in one:

1. The `Collector` expects the action to be a `torch.item()` rather than a `torch.Tensor` when `categorical_action_encoding=True`. 
2. When `categorical_action_encoding=False` but we pass incorrect shapes, the Collector will silently fail instead of crashing and emitting an error.

Bug 2 is quite insidious -- if your model outputs integer actions instead of one hot, the collector will always select the first action, regardless of what the model output. This can lead users to think that something is wrong with their algorithm.

# To Reproduce
```python
# Part 1
from torchrl.collectors import SyncDataCollector
import random
def policy(data):
    # Action should be the same shape as reward, done, etc...
    data["action"] = torch.randint(0, 2, data["done"].shape)
    return data

env = GymEnv("CartPole-v0", categorical_action_encoding=True)
collector = SyncDataCollector(env, policy)
for data in collector:
    pass
```
```bash
Traceback (most recent call last):
  File "/Users/smorad/r4l_torch/examples/test_dqn.py", line 23, in <module>
    for data in collector:
  File "/Users/smorad/miniforge3/envs/torch_rl/lib/python3.9/site-packages/torchrl/collectors/collectors.py", line 535, in iterator
    tensordict_out = self.rollout()
  File "/Users/smorad/miniforge3/envs/torch_rl/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/smorad/miniforge3/envs/torch_rl/lib/python3.9/site-packages/torchrl/collectors/collectors.py", line 658, in rollout
    self._tensordict = self.env.step(self._tensordict)
  File "/Users/smorad/miniforge3/envs/torch_rl/lib/python3.9/site-packages/torchrl/envs/common.py", line 380, in step
    tensordict_out = self._step(tensordict)
  File "/Users/smorad/miniforge3/envs/torch_rl/lib/python3.9/site-packages/torchrl/envs/gym_like.py", line 183, in _step
    self._env.step(action_np)
  File "/Users/smorad/miniforge3/envs/torch_rl/lib/python3.9/site-packages/gym/wrappers/time_limit.py", line 50, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
  File "/Users/smorad/miniforge3/envs/torch_rl/lib/python3.9/site-packages/gym/wrappers/order_enforcing.py", line 37, in step
    return self.env.step(action)
  File "/Users/smorad/miniforge3/envs/torch_rl/lib/python3.9/site-packages/gym/envs/classic_control/cartpole.py", line 132, in step
    assert self.action_space.contains(action), err_msg
AssertionError: array([1]) (<class 'numpy.ndarray'>) invalid
```

Calling `.item()` fixes this, but then the `action` is no longer a tensor.

```python
def policy(data):
    data["action"] = torch.randint(0, 2, data["done"].shape).item()
    return data
```

```python
# Part 2

from torchrl.collectors import SyncDataCollector
import random
def policy(data):
    data["action"] = torch.randint(0, 2, data["done"].shape) # We are outputting shape=[1]
    # Collector should crash because it expects shape=[2], but instead it will silently always pick the first action.
    return data

env = GymEnv("CartPole-v0", categorical_action_encoding=False)
collector = SyncDataCollector(env, policy)
for data in collector:
    pass # No error!! This should throw an error!
```

## Expected behavior

1. The collector should expect action to be a tensor of shape `(1,)` like reward, done, etc.
2. The collector should error if the shape of a one hot vector is not the shape of the categorical space

## System info
```
None 1.22.1 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:01:00)
[Clang 13.0.1 ] darwin
```

## Reason and Possible fixes

If you know or suspect the reason for this bug, paste the code lines and suggest modifications.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
(It's a classical messed-up thing from gym if you want my opinion: lack of convention across envs which make it hard to write reusable code without complicated control flow)
 
CartPole expects a zero-dim tensor as action. 
In TorchRL the convention is that done and reward tensors end up with a singleton dimension. The reason is we want to be able to do
```
value = network(observation)
next_val = reward + gamma * done * value
```
Since `network` will most likely output a tensor with a tailing singleton dim, we believe it's easier to have reward and done do the same.
I believe your example should work with 

```python
from torchrl.collectors import SyncDataCollector
import random
def policy(data):
    data["action"] = torch.randint(0, 2, data.shape) # We are outputting shape=[1]
    # Collector should crash because it expects shape=[2], but instead it will silently always pick the first action.
    return data

env = GymEnv("CartPole-v0", categorical_action_encoding=False)
collector = SyncDataCollector(env, policy)
for data in collector:
    pass # No error!! This should throw an error!
```

**Comment by smorad** [comment]
Why does part 2 not crash though? It is expecting an array of size 2 (index). I pass it a size 1 tensor and the collector somehow encodes this (incorrectly). This could be a pitfall for new users because it is not immediately clear if TorchRL uses the categorical/index encoding.
